language: node_js
node_js:
  - "4"
  - "5"
  - "stable"
sudo: false
services:
  - mongodb
before_script:
  - export NODE_ENV=ci
  - export TEST_TIMEOUT_MULTIPLY=10.0
  - sleep 5 # give mongod time to startup
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
